#!/bin/bash
### BEGIN INIT INFO
# Provides:           clusterstatd
# Required-Start:     $local_fs $remote_fs $network
# Required-Stop:      $local_fs $remote_fs $network
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  ClusterStat Daemon
# Description:        This script collects status data for shared hosting.
### END INIT INFO

PHP=$(which php)
SCRIPT="/usr/share/clusterstat-daemon/clusterstatd.php"
NAME="ClusterStat Daemon"

test $PHP || { echo "PHP is not found"; exit 0; }
test -x $PHP || { echo "PHP is not executable: $PHP"; exit 0; }
test -f $SCRIPT || { echo "Main ClusterStatD script not found: $SCRIPT"; exit 0; }

set -e

start() {
        echo "Starting $NAME ..."
        $PHP -d disable_functions= -f $SCRIPT -- start
}
stop() {
        echo "Stopping $NAME ..."
        $PHP -d disable_functions= -f $SCRIPT -- stop
}
restart() {
        echo "Restarting $NAME..."
        stop
        start
}
case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                restart
                ;;
        *)
                echo "Usage $0 {start|stop|restart}"
                RETVAL=1
esac
